#!/usr/bin/bash
#
# This dotfile holds all general, non-work-related settings, aliases, functions, etc.
#

############################
### Settings / Variables ###
############################

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

#export PS1='\[\033[1;32m\]\u@\h \[\033[1;34m\]\W\[\033[1;35m\]$(__git_ps1 " (%s)") \[\033[1;37m\]\$ '

export VISUAL=emacsclient
export EDITOR="$VISUAL"

###############
### Aliases ###
###############

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
# Add an "alert" alias for long running commands.  Use like so: [sleep 10; alert]
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias alg='alias -p | grep'
alias back='cd -'
alias cl='clear'
alias fn="find . -name"
alias gr="ag --color-path 1\;36"
alias l='ls -al'
alias psg='ps aux | grep'
alias src='source ~/.bashrc'
alias tf='tail -F'

#################
### Functions ###
#################

# function e {
#     EMACS=/usr/local
#     $EMACS/bin/emacsclient --no-wait -a="$EMACS/emacs" $1 &
# }
function e {
    /usr/local/bin/emacsclient --alertnate-editor="/usr/local/bin/emacs" -c "$@" &
}
# function e2 {
#     emacsclient -n -a="~/Applications/Emacs" $1 &
# }

function ips {
    RED='\033[00;31m'
    GREEN='\033[00;32m'
    RESET='\033[00m'

    for i in `seq 1 255`; do
        IP=$1.$i
        RES=$(ping -c 1 -W 1 $IP | tr \\n ' ')
        if echo $RES | grep -q '1 packets received'; then
            echo -e "[ ${RED}TAKEN${RESET} ] $IP";
        else
            echo -e "[ ${GREEN}AVAIL${RESET} ] $IP";
        fi
    done

    unset RED
    unset GREEN
    unset RESET
}

function join_by {
    local IFS="$1";
    shift;
    echo "$*";
}

function mkd {
    mkdir $1
    cd $1
}

function ra {
    for FILE in `grep -Irl $1 $3`
    do
        perl -pi -e "s|$1|$2|" $FILE
    done
}

function wwc {
    tail -F $1 | egrep --color "$2|$"
}

SSH_ENV="$HOME/.ssh/environment"
function start_agent {
    echo "Initialising new SSH agent..."
    ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo "Success"
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
}
